name: background_timer
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  audioplayers: ^5.1.0
  # device_info_plus: ^9.0.3
  device_info_plus: ^8.0.0
  flutter:
    sdk: flutter
  # flutter_background_service: ^5.0.1
  flutter_fgbg: ^0.3.0
  flutter_local_notifications: ^15.1.0+1
  shared_preferences: ^2.2.0
  # timer_count_down: ^2.2.2

  flutter_background_service:
    git:
      url: https://github.com/a-mabe/flutter_background_service.git
      ref: stop-on-app-close # branch name
      path: ./packages/flutter_background_service

  flutter_background_service_android:
    git:
      url: https://github.com/a-mabe/flutter_background_service.git
      ref: stop-on-app-close # branch name
      path: ./packages/flutter_background_service_android
  audio_session: ^0.1.16
  just_audio: ^0.9.35

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  flutter_background_service:
    git:
      url: https://github.com/a-mabe/flutter_background_service.git
      ref: stop-on-app-close # branch name
      path: ./packages/flutter_background_service

  flutter_background_service_android:
    git:
      url: https://github.com/a-mabe/flutter_background_service.git
      ref: stop-on-app-close # branch name
      path: ./packages/flutter_background_service_android

  # flutter_background_service_ios:
  #   git:
  #     url: https://github.com/a-mabe/flutter_background_service.git
  #     ref: stop-on-app-close # branch name
  #     path: ./packages/flutter_background_service_ios

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - packages/background_timer/assets/audio/

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
